config/routes.rb
Rails.application.routes.draw do
  resources :fotos
  devise_for :users
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foto.rb
class Foto < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :fotos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :create, :destroy, :update]
  before_action :check_user, only: [:edit, :destroy, :update]

  def index
    @fotos = Foto.all.order("created_at DESC")
  end

  def show
  end

  def new
    @foto = current_user.fotos.build
  end

  def edit
  end

  def create
    @foto = current_user.fotos.build(foto_params)
    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Zdjęcie skutecznie dodane !' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Zdjęcie zmienione !' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Zdjęcie skutecznie usunięte !' }
      format.json { head :no_content }
    end
  end

  private
    def set_foto
      @foto = Foto.find(params[:id])
    end

    def foto_params
      params.require(:foto).permit(:description, :image)
    end


    private
      def check_user
        foto = Foto.find(params[:id])
        if current_user == foto.user
          true
        else
          redirect_to foto_path(foto)
        end
      end
      # Use callbacks to share common setup or constraints between actions.
      def set_foto
        @foto = Foto.find(params[:id])
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fotos/_form.html.erb
<div class="container form">
<div class="formRender">
<%= form_for @foto, html: { multipart: true } do |f| %>
  <% if foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :Tytuł %><br>
    <%= f.text_field :description %>
  </div>
</div>
<div class="form-group">
  <div class="form-group">
  <%= f.label :image, "Fotka" %>
  <%= f.file_field :image, class: "form-control" %>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>

</div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing Foto</h1>

<%= render 'form', foto: @foto %>

<%= link_to 'Pokaż', @foto %> |
<%= link_to 'Powrót', fotos_path %>

app/views/fotos/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "container-fluid">
  <div class="main">
        <!-- <div class="container table"> -->
          <div class="transitions-enabled">
            <% @fotos.each do |foto| %>
              <div class="box">
                <div class="panel panel-default">
                          <%= link_to image_tag(foto.image.url(:medium)), foto %><br/>
                          <%= foto.description %><br/>
                </div>
                          <% if foto.user == current_user %>
                <div class="panel-footer">
                          <%= link_to 'Edytuj', edit_foto_path(foto) %> |
                          <%= link_to 'Usuń', foto, method: :delete, data: { confirm: 'Jesteś pewny ?' } %>

                </div>
                          <% end %>
              </div>
                          <% end %>
                          <%= link_to '+', new_foto_path %>

            </div>

<div style="clear:both"></div>
  <br>
          <div class="singn">
            <div class="row">
                  <div class="col-md-4 col-xs-4">
                  </div>

                <div class="col-md-4 col-xs-4">
                    <div class="plus text-center">
                      <span class="add">
                        <%= link_to '+', new_foto_path %>
                      </span>
                    </div>
                </div>

                <div class="col-md-4 col-xs-4">
                </div>
          </div>
        </div>


  </div>
</div>

app/views/fotos/new.html.erb
<div class="fotos">

<div class="container">
<h1 id="smialo">Dodaj nowe zdjęcie - śmiało</h1>

<%= render 'form', foto: @foto %>

<%= link_to 'Powrót', fotos_path %>
</div>
</div>

app/views/fotos/show.html.erb
          <h1>Zobacz</h1>
                <div class="container">
                  <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                      <div class="panel panel-default">
                          <div class="panel-heading center"><%= image_tag @foto.image.url(:medium) %>
                              <%= @foto.description %>
                          </div>
                                <div class="panel-body">
                                    <% if @foto.user == current_user %>
                                    <%= link_to 'edytuj', edit_foto_path(@foto) %> |
                                    <% end %>
                                    <%= link_to 'wstecz', fotos_path %>
                               </div>
                     </div>
                    </div>
                </div>
              </div>

app/views/home/_header.html.erb
<br><br>

<div class="container-fluid">
  <nav class="navbar navbar-inverse shadow" role="navigation">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> -->
                <!-- <span class="sr-only">Toggle navigation</span> -->
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand logo" href="#">Fotki<span id="fotki">24</span></a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Start', root_path %></li>
            <li><%= link_to 'O mnie', home_about_path %></li>
            <li><%= link_to 'Lista zdjęć', fotos_path %>

            <% if user_signed_in? %>
                  <li><%= link_to 'Edytuj profil', edit_user_registration_path %></li>
                  <li><%= link_to 'Wyloguj', destroy_user_session_path, method: :delete %></li>
                  <li><%= link_to 'Dodaj fotkę', new_foto_path %></li>
            <% else %>
                  <li><%= link_to "Login", new_user_session_path %></li>
                  <li><%= link_to "Rejestracja", new_user_registration_path %></li>
          <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->

</nav>
</div><!-- /.container-->

app/views/home/about.html.erb
        <div class="jumbotron">
                <h1 id="anim01" class="animated bounceInRight">My name is Piotr</h1></br>
                <p id="anim02" class="animated bounceInRight">Still I am creating this section...</p>  <br>
              <%= link_to 'Home', root_path, class: 'btn btn-success btn-lg animated bounceInRight anim03' %>
              <span class="glyphicon glyphicon-menu-down arrow animated infinite slideOutDown" aria-hidden="true"></span>




        </div>
<div id="skils">
      <div class="container-fluid text-center">
        <br><br>
              <h1 id="anim" class="animated infinite bounceIn">Skills</h1>
              <h3>What can I offer to you ?</h3>
              <br><br>
              <div class="row">
                  <div class="col-sm-4 col-xs-4">
                    <i class="fa fa-html5 fa-5x" aria-hidden="true"></i>
                    <h4 class="animated tada anim2">HTML,HTML5</h4>
                    <br>
                  </div>
                  <div class="col-sm-4 col-xs-4">
                    <i class="fa fa-css3 fa-5x" aria-hidden="true"></i>
                    <h4 class="animated tada anim1">CSS/SASS</h4>
                  </div>

                  <div class="col-sm-4 col-xs-4">
                    <i class="fa fa-wordpress fa-5x" aria-hidden="true"></i>
                    <h4 class="animated tada anim3">WORDPRESS</h4>
                  </div>
              </div>


                  <br><br>

              <div class="row">
                <br>
                  <div class="col-sm-4">
                   <img src="https://s3.eu-central-1.amazonaws.com/about24/ruby_logo.png">
                    <h4 class="animated tada anim1">RUBY ON RAILS</h4>
                  </div>
                  <br>
                  <div class="col-sm-4">
                    <img src="https://s3.eu-central-1.amazonaws.com/about24/jquery_logo.png">
                    <h4 class="animated  tada anim3">JS and  JQUERY  </h4>
                  </div>
                  <div class="col-sm-4">
                    <img src="https://s3.eu-central-1.amazonaws.com/about24/photoshop_logo.png">
                    <h4 class="animated tada anim2">PHOTOSHOP</h4>
                  </div>
              </div>

                  <br><br>
              <div class="row">
                <br><br><br>
                  <div class="col-sm-4 col-xs-4">
                    <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
                    <h4 class="animated tada anim2">MAC</h4>
                  </div>

                  <div class="col-sm-4 col-xs-4">
                    <i class="fa fa-github fa-5x" aria-hidden="true"></i>
                    <h4 class="animated tada anim3">GITHUB</h4>
                  </div>

                  <div class="col-sm-4 col-xs-4">
                    <i class="fa fa-users fa-5x" aria-hidden="true"></i>
                    <h4 class="animated tada anim1">TEAMWORK</h4>
                  </div>
              </div>
              <br><br><br><br>

      </div>

</div>

app/views/home/index.html.erb
<div class="contiainer">
  <div class="main">
    <div class="jumbotron first">
            <h1 id="anim01" class="animated bounceInRight">Dodawaj i przeglądaj zdjęcia</h1>
            <p id="anim02" class="animated bounceInRight">Dodanie zdjęcia wymaga rejestracji</p>
            <%= link_to 'Rejestracja', new_user_registration_path, class: 'btn btn-primary btn-lg animated bounceInRight anim03' %>


            <div class="singn animated fadeInUpBig anim03">
              <div class="row">
                    <div class="col-md-4 col-xs-4">
                    </div>

                  <div class="col-md-4 col-xs-4">
                      <div class="plus text-center">
                        <span class="add">
                          <%= link_to '+', new_foto_path %>
                        </span>
                      </div>
                  </div>

                  <div class="col-md-4 col-xs-4">
                  </div>
            </div>
          </div>

    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotki24</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="animate.min.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/header' %>
  <div class="container-fluid height">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alertinfo yellow")%>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>